name: Test github Actions
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install and Build
        run: |
          if [ -e 'package-lock.json' ]; then 
          npm ci
          else 
          npm install
          fi
          npm run deploy-storybook -- --ci
        env :
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          